sudo: false

language: java

env:  
  global:
    - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
- dpkg -l libgtk2.0-0 libgtk-3-0
- mvn -Pnu -Pgui clean package

after_failure:
- find -name "*.txt" | grep -F 'surefire-reports' | xargs cat
